name: 'Promptfoo Code Scan'
description: 'Scan pull requests for LLM security vulnerabilities'
author: 'Promptfoo, Inc.'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  server-url:
    description: 'Code scan server URL'
    required: false
    default: 'https://api.promptfoo.dev'
  minimum-severity:
    description: 'Minimum severity level to report (low|medium|high|critical)'
    required: false
    default: 'high'
  fail-on-vulnerabilities:
    description: 'Fail the workflow if vulnerabilities are found (false|high|critical)'
    required: false
    default: 'false'
  config-path:
    description: 'Path to YAML configuration file'
    required: false
  github-token:
    description: 'GitHub token for authentication (default: github.token)'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
